language:
  - php

php:
  - 5.4
  - 5.5
  - 5.6

services:
    - elasticsearch
    - mongodb
    - rabbitmq
    - redis-server

before_install:
    - sudo apt-get update > /dev/null
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

install:
    - sudo curl -O 'http://skylink.dl.sourceforge.net/project/wkhtmltopdf/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb'
    - sudo dpkg -i ./wkhtmltox-0.12.1_linux-precise-amd64.deb
    - sudo apt-get install -y --force-yes openssl build-essential xorg libssl-dev apache2 libapache2-mod-php5 php5-curl php5-intl > /dev/null
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - sudo /etc/init.d/apache2 restart

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - export MINK_EXTENSION_PARAMS='base_url=http://localhost:8000/app_test.php'
    - composer self-update
# Composer install's clear cache hook now throws 'unknown database' error
    - mysql -e 'create database application;'
    - composer install --prefer-source --no-interaction
    - composer require doctrine/mongodb-odm="1.0.*@dev" --no-update
    - composer require jmikola/geojson="~1.0" --no-update
    - composer update doctrine/mongodb-odm jmikola/geojson --prefer-source --no-interaction
#    - app/console doctrine:database:create --env=test > /dev/null
    - app/console doctrine:schema:create --env=test > /dev/null
    - app/console doctrine:fixtures:load -n --env=test > /dev/null
    - app/console fos:elastica:populate
    - app/console cache:warmup --env=test > /dev/null
    - nohup /usr/bin/env php app/console rabbitmq:consumer message --env=test &
    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99
    - sleep 5

script:
    - bin/phpspec run -f dot
    - php -d memory_limit=2048M bin/behat --suite=endroid_api --no-snippets --verbose
    - php -d memory_limit=2048M bin/behat --suite=endroid_messaging --no-snippets --verbose
    - php -d memory_limit=2048M bin/behat --suite=endroid_pdf --no-snippets --verbose
    - php -d memory_limit=2048M bin/behat --suite=endroid_site --no-snippets --verbose

notifications:
    email: "info@endroid.nl"
